version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: teebay
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    build:
      context: ./teebay-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/teebay
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db

  frontend:
    build:
      context: ./teebay-ui
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    environment:
      VITE_API_URL: "http://api:8080"
    depends_on:
      - api

volumes:
  db-data:
